source 'https://rubygems.org'

gem 'rake'
gem 'rspec'
gem 'capybara'
gem 'selenium-webdriver'
gem 'chromedriver-helper'
gem 'nationbuilder-rb'
gem 'oauth2'
gem 'pry'
gem 'poltergeist'
gem 'launchy'
gem 'activesupport'